package edu.children.xiaoshizi.logic;

public enum  APIMethod {
    getVerifyCode,
    login,
    loadSysBannerList,
    loadContentCategory,
    loadSchoolData,
    getStudentsAndParents,
    studentBinding,
    verifiedSubmit,
    getMyProfile,
    saveMyProfile,
    findStudentSnapMsg,
    findSnapMsgById,
    doSnapMsgFeedBack,
    loadContentByCategory,
    loadContentById,
    loadSeLabContentCategory,
    loadSafeLabContentByCategory,
    loadSafeLabContentById,
    loadSeClassRoomContentCategory,
    loadSeClassRoomContentByCategory,
    loadSeClassRoomContentById,
}
