package edu.children.xiaoshizi.logic;

public enum  APIMethod {
    getVerifyCode,
    validSmsVCode,
    login,
    loginOut,
    loadSysBannerList,
    loadContentCategory,
    loadSchoolData,
    getStudentsAndParents,
    studentBinding,
    studentUnBinding,
    verifiedSubmit,
    getMyProfile,
    saveMyProfile,
    findStudentSnapMsg,
    findSnapMsgById,
    doSnapMsgFeedBack,
    loadContentByCategory,
    loadContentById,
    searchContentByTitle,
    loadSeLabContentCategory,
    loadSafeLabContentByCategory,
    loadSafeLabContentById,
    loadSeClassRoomContentCategory,
    loadSeClassRoomContentByCategory,
    loadSeClassRoomContentById,
    submitFeedBack,
    submitDraftContent,
    submitComment,
}
